baseurl = "https://kevintjeb.github.io"
title = "Kevin van den Broek"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Kevin van den Broek"

[params]
    author = "Kevin van den Broek"
    description = "Kevin van den Broek portfolio"
    keywords = "blog,developer,personal"
    info = "Full Stack Software Engineer"
    avatarurl = "images/N90.jpg"
    footercontent = "I am a hard-working, enthusiastic, self-motivated and involved software engineer that takes on any challenge and tries to get the best results out of it!"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/kevintjeb/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/kevin_watch/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/kevin-van-den-broek-9b768b132/"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"

